Name: Ishita Jindal

Reg. no.: 21BCB0061

Email: ishita.jindal2021@vitstudent.ac.in




Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [1]:
import numpy as np
import pandas as pd

data = np.random.rand(4, 4)

df = pd.DataFrame(data)

df

          0         1         2         3
0  0.598435  0.341144  0.025259  0.410678
1  0.248760  0.328508  0.678570  0.099297
2  0.258641  0.357832  0.992340  0.583719
3  0.070963  0.119913  0.066038  0.355225

Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [2]:
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']

df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.598435        0.341144        0.025259        0.410678
1        0.248760        0.328508        0.678570        0.099297
2        0.258641        0.357832        0.992340        0.583719
3        0.070963        0.119913        0.066038        0.355225

Task - 3 Find the descriptive statistics of the 'df' dataframe

In [3]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.294200        0.286849        0.440552        0.362230
std          0.220396        0.111937        0.473938        0.200489
min          0.070963        0.119913        0.025259        0.099297
25%          0.204311        0.276359        0.055843        0.291243
50%          0.253701        0.334826        0.372304        0.382952
75%          0.343589        0.345316        0.757013        0.453938
max          0.598435        0.357832        0.992340        0.583719

Task - 4 Check for the null values in 'df' and find the data type of the columns

In [4]:
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [5]:
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [6]:
df.iloc[:, 1:3]

   Random value 2  Random value 3
0        0.341144        0.025259
1        0.328508        0.678570
2        0.357832        0.992340
3        0.119913        0.066038

In [7]:
df.loc[:, ['Random value 2', 'Random value 3']]

   Random value 2  Random value 3
0        0.341144        0.025259
1        0.328508        0.678570
2        0.357832        0.992340
3        0.119913        0.066038